backend:
  name: github
  repo: NodeJSs/My-Blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: Blog Posts
    create: true
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { name: slug, label: Path(slug) }
      - { name: date, label: Date, widget: date, format: "DD MMMM, YYYY" }
      - { name: dateForSorting, label: Date For Sorting, widget: date}
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: "list", default: ["Blog Post"], field: {label: "Tag", name: "tag_name", widget: "text"},required: false }
      - { name: excerpt, label: Excerpt }
      - { name: image, label: Image, widget: image, default: "", required: false }
      - { name: body, label: Body, widget: markdown }

  - name: Unfinished Blog Posts
    label: Unfinished Blog Posts
    folder: Unfinished Blog Posts
    create: true
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { name: slug, label: Path(slug) }
      - { name: date, label: Date, widget: date, format: "DD MMMM, YYYY" }
      - { name: dateForSorting, label: Date For Sorting, widget: date}
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: "list", default: ["Blog Post"], field: {label: "Tag", name: "tag_name", widget: "text"}, required: false }
      - { name: excerpt, label: Excerpt }
      - { name: image, label: Image, widget: image, default: "", required: false }
      - { name: body, label: Body, widget: markdown }