backend:
  name: github
  repo: NodeJSs/My-Blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: Blog Posts
    create: true
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date, format: "DD MMMM, YYYY" }
      - { name: title, label: Title }
      - { name: tags, label: Tags }
      - { name: excerpt, label: Excerpt }
      - { name: image, label: Image, widget: image, default: "" }
      - { name: body, label: Body, widget: markdown }